namespace LBPRDC.Source.Utilities
{
    internal class FileFormatConstants
    {
        public static readonly List<string> addBatchFormat = new()
        {
            "EMPLOYEE ID",
            "LAST NAME",
            "FIRST NAME",
            "MIDDLE NAME",
            "SUFFIX",
            "GENDER",
            "BIRTHDAY",
            "EDUCATION",
            "DEPARTMENT",
            "EMAIL ADDRESS 1",
            "EMAIL ADDRESS 2",
            "CONTACT NUMBER 1",
            "CONTACT NUMBER 2",
            "CIVIL STATUS",
            "POSITION",
            "POSITION TITLE",
            "START DATE",
            "NEW POSITION",
            "NEW POSITION TITLE",
            "EFFECTIVE DATE",
            "EMPLOYMENT STATUS"
        };

        public static readonly List<string> ExcelTimekeepWorksheetFormat = new()
        {
            "Scanning Number",
            "Name",
            "Date",
            "PAYROLL DOCS FILE NAME",
            "PAYROLL DOCS FILE NAME",
            "Regular Hours",
            "Legal Holiday -UNWORKED",
            "Reg OT",
            "Rest Day OT",
            "RDOT Excess",
            "Special Holiday OT",
            "Special Holiday Excess OT",
            "Legal Holiday OT",
            "Legal Holiday OT",
            "Rest Day OT",
            "Reg Holiday OT",
            "TOTAL OT",
            "Night Differential",
            "Night Differential",
            "Night Differential",
            "Night Differential",
            "Night Differential",
            "Night Differential",
            "TOTAL NDOT",
            "UT",
            "Absent"
        };

        public static readonly List<string> ExcelReportWorksheetFormat = new()
        {
            "PAYROLL COMPUTATION - SHFC"
        };

        public static readonly List<string> ExcelAccrualsWorksheetFormat = new()
        {
            "",
            "",
            "Name",
            "POSITION",
            "Hourly Rate",
            "Billing Rate",
            "# of worked days",
            "Hours",
            "Reg Bill Wrk days",
            "UTIME",
            "Net Reg Bill",
            "Factor",
            "Reg OT (125%)",
            "",
            "Factor",
            "Rest day OT (130%)",
            "",
            "Factor",
            "RDSHOT (150%)",
            "",
            "Factor",
            "SHOT Excess (169%)",
            "",
            "Emp. No.",
            "",
            "",
            "Factor",
            "LHOT (200%)",
            "",
            "Factor",
            "RDLHOT (260%)",
            "",
            "Factor",
            "RDLHOT EXCESS (338%)",
            "",
            "Factor",
            "Hrs:Mins",
            "",
            "Factor",
            "Hrs:Mins",
            "",
            "Factor",
            "Hrs:Mins",
            "",
            "Emp. No.",
            "Hrs:Mins",
            "Amount",
            "Factor",
            "NDOT (12.5%)",
            "",
            "Factor",
            "NDOT (13.0%)",
            "",
            "Factor",
            "Hrs:Mins",
            "",
            "Factor",
            "Hrs:Mins",
            "",
            "Factor",
            "Hrs:Mins",
            "",
            "Factor",
            "Hrs:Mins",
            "",
            "Emp. No.",
            "Factor",
            "Hrs:Mins",
            "",
            "Factor",
            "Hrs:Mins",
            "",
            "TOTAL OT",
            "Gross Billing"
        };
    }
}
